# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['nba_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ("Data/cleaned_player_playoffs_careers.csv", "Data"),
        ("Data/cleaned_player_regular.csv", "Data"),
        ("Data/teams_season_cleaned.txt", "Data"),
        ("Data/teams.txt", "Data"),
        ("Data/top20_iso_outliers.csv", "Data"),
        ("Images/iso_outliers.png", "Images"),
        ("Models/isoForest_model.pkl", "Models"),
        ("Models/scaler.pkl", "Models"),
        ("Models/stack_model.pkl", "Models"),
        ],
    hiddenimports=[
        'sklearn.preprocessing',
        'sklearn.decomposition',
        'sklearn.svm',
        'sklearn.ensemble',
        'sklearn.model_selection',
        'sklearn.metrics',
        'sklearn.pipeline',
        'sklearn.cluster',
        'sklearn.linear_model',
        'sklearn.base',
        'sklearn.calibration',
        'xgboost',
        'joblib',
        'matplotlib.pyplot',
        'itertools',
        'collections',
        ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='NBA_Predictor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
